Description: >
      Randall Granier / Udacity Course
      PROJECT X:  Single EC2
      ./create.sh TestStack3 myservers3.yml myserverparams3.json
      ./update.sh TestStack3 myservers3.yml myserverparams3.json

Parameters:

  EnvironmentName:
      Description: The environment name for this stack.
      Type: String

Resources:
  ProfileWithRolesForOurApp:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - UdacityGranierEC2S3

  TestSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH to server only
      VpcId: vpc-187fc27d
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0

  MyEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-003634241a8fcdec0
      KeyName: "GranierConsulting"
      SecurityGroupIds:
        - !GetAtt TestSecGroup.GroupId

      Tags:
        - Key: Name
          Value: MyEC2Instance
        - Key: Type
          Value: Test3Instance
