FROM python:3.7.3-stretch

## Step 1:
# Create a working directory
WORKDIR /app

## Step 2:
# Copy source code to working directory
# We don't actually have to add the output directories because we are not Logging
# directly to the files, but rather cutting and  pasting in our project.
#ADD output_txt_files /app/output_txt_files
COPY model_data/*  /app/model_data/
COPY app.py /app/
COPY requirements.txt /app/

## Step 3:
# Install packages from requirements.txt
# hadolint ignore=DL3013
RUN pip install --upgrade pip &&\
    pip install --trusted-host pypi.python.org -r requirements.txt

## Step 4:
# Expose port 80
EXPOSE 80

## Step 5:
# Run app.py at container launch
CMD ["python", "app.py"]
