apiVersion: apps/v1
kind: Deployment
metadata:
  name: newtest
  labels:
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: microservicerepo
        image: rgranier/microservicerepo
        ports:
        - containerPort: 80
