apiVersion: apps/v1
kind: Deployment
metadata:
  name: myk8ms
  labels:
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: microservicerepo
        image: rgranier/microservicerepo
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myk8ms2-svc
  labels:
    env: dev
spec:
  type: LoadBalancer
  ports:
  - port: 81
  selector:
    env: dev
