Description: >
      Randall Granier / Udacity Course
      PROJECT X:  Single EC2
      ./create.sh TestStack myservers.yml myserverparams.json
      ./update.sh TestStack myservers.yml myserverparams.json

Parameters:

  EnvironmentName:
      Description: The environment name for this stack.
      Type: String

Resources:
  ProfileWithRolesForOurApp:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - UdacityGranierEC2S3

  TestSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH to server only
      VpcId: vpc-187fc27d
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-003634241a8fcdec0"
      KeyName: "GranierConsulting"
      VpcId: vpc-187fc27d
      SecurityGroups:
      - Ref: TestSecGroup
      InstanceType: t2.micro
      BlockDeviceMappings:
      - DeviceName: "/dev/sdk"
        Ebs:
          VolumeSize: '10'
